"""
UserProfile model for user identity and authentication.

UserProfile stores user identity information and authentication credentials.
This table is self-contained and stores hashed passwords for custom JWT auth.

Schema Reference:
- migrations/001_initial_schema.sql lines 36-43
- migrations/011_custom_auth_migration.sql (adds hashed_password)
"""
from datetime import datetime
from typing import TYPE_CHECKING, Optional
from uuid import UUID

from sqlalchemy import String, ForeignKey, Index
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base
from app.models.base import TimestampMixin

if TYPE_CHECKING:
    from app.models.role import Role
    from app.models.student import Student
    from app.models.teacher import Teacher


class UserProfile(Base, TimestampMixin):
    """
    UserProfile entity for user identity and authentication.
    
    Attributes:
        id: Primary key UUID (generated by application after migration 011)
        email: Unique email address for login
        full_name: User's display name
        role_id: Foreign key to roles table (optional)
        hashed_password: BCrypt hashed password for authentication
        created_at: Timestamp when profile was created
        updated_at: Timestamp of last modification
        
    Relationships:
        role: The user's Role entity
        student: Student record if user is a student (one-to-one)
        teacher: Teacher record if user is a teacher (one-to-one)
    """
    __tablename__ = "user_profiles"
    
    # Primary key - UUID generated by application (no longer FK to auth.users)
    id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        primary_key=True,
        comment="User UUID - generated by application",
    )
    
    # Identity fields
    email: Mapped[str] = mapped_column(
        String,
        unique=True,
        nullable=False,
        index=True,
    )
    full_name: Mapped[str] = mapped_column(String, nullable=False)
    
    # Role relationship
    role_id: Mapped[Optional[int]] = mapped_column(
        ForeignKey("roles.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    
    # Authentication - added in migration 011
    hashed_password: Mapped[Optional[str]] = mapped_column(
        String,
        nullable=True,  # Nullable for backward compatibility with existing users
        comment="BCrypt hashed password for authentication",
    )
    
    # Relationships
    role: Mapped[Optional["Role"]] = relationship(
        "Role",
        back_populates="users",
        lazy="selectin",  # Load related Role on access with separate query
    )
    
    student: Mapped[Optional["Student"]] = relationship(
        "Student",
        back_populates="user",
        uselist=False,  # One-to-one relationship
        lazy="selectin",
    )
    
    teacher: Mapped[Optional["Teacher"]] = relationship(
        "Teacher",
        back_populates="user",
        uselist=False,  # One-to-one relationship
        lazy="selectin",
    )
    
    # Additional indexes defined in migration
    __table_args__ = (
        Index("idx_user_profiles_email_unique", "email", unique=True),
    )
    
    def __repr__(self) -> str:
        return f"<UserProfile(id={self.id}, email='{self.email}', role_id={self.role_id})>"
