-- Migration: 011_custom_auth_migration
-- Created: 2026-01-07
-- Description: Migrate from Supabase Auth to custom JWT-based authentication
-- 
-- This migration:
-- 1. Adds hashed_password column to user_profiles
-- 2. Removes the dependency on auth.users table
-- 3. Updates the user_profiles table to be self-contained for authentication
-- 4. Removes the trigger that created user_profiles from auth.users

-- ============================================================================
-- STEP 1: Add hashed_password column to user_profiles
-- ============================================================================

-- Add hashed_password column (nullable initially for existing users)
ALTER TABLE user_profiles
ADD COLUMN IF NOT EXISTS hashed_password TEXT;

-- ============================================================================
-- STEP 2: Remove the trigger on auth.users (no longer needed)
-- ============================================================================

-- Drop the trigger that auto-created user_profiles from auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

-- Drop the trigger function (no longer needed)
DROP FUNCTION IF EXISTS handle_new_user();

-- ============================================================================
-- STEP 3: Modify user_profiles to be standalone
-- ============================================================================

-- Remove the foreign key constraint on auth.users
-- First, we need to drop the constraint if it exists
-- Note: This may fail if the constraint doesn't exist or has a different name
DO $$ 
BEGIN
    -- Try to drop the foreign key constraint
    ALTER TABLE user_profiles DROP CONSTRAINT IF EXISTS user_profiles_id_fkey;
EXCEPTION
    WHEN OTHERS THEN
        -- Constraint might not exist or have a different name, that's OK
        NULL;
END $$;

-- Change the id column to not reference auth.users anymore
-- The id will now be generated by the application (UUID)
COMMENT ON COLUMN user_profiles.id IS 'User UUID - generated by application, no longer references auth.users';

-- ============================================================================
-- STEP 4: Create index on email for faster login lookups
-- ============================================================================

-- Ensure we have a unique index on email (should already exist)
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_profiles_email_unique ON user_profiles(email);

-- ============================================================================
-- STEP 5: Add check constraint for hashed_password (for new users)
-- ============================================================================

-- Note: We don't add a NOT NULL constraint on hashed_password yet
-- because existing users from Supabase Auth don't have one
-- This should be handled during data migration

-- ============================================================================
-- STEP 6: Revoke permissions from supabase_auth_admin (no longer needed)
-- ============================================================================

-- These permissions were for the trigger to work
-- They are no longer needed since we don't use Supabase Auth
DO $$ 
BEGIN
    REVOKE ALL ON public.user_profiles FROM supabase_auth_admin;
    REVOKE ALL ON public.students FROM supabase_auth_admin;
    REVOKE ALL ON public.teachers FROM supabase_auth_admin;
EXCEPTION
    WHEN OTHERS THEN
        -- Role might not exist, that's OK
        NULL;
END $$;
