from app.models.base import Base
from app.models.role import Role
from app.models.user import UserProfile
from app.models.teacher import Teacher
from app.models.school import School
from app.models.major import Major
from app.models.class_model import Class
from app.models.student import Student
from app.models.interview_session import InterviewSession
from app.models.document import Document
from app.models.interview_score import InterviewScore
from app.models.summary import InterviewSummary
from app.models.detailed_feedback import InterviewDetailedFeedback
from app.models.next_step import InterviewNextStep
